name: Build Directus on FreeBSD

on:
  workflow_dispatch:   # 手动触发
  push:                # push 到 main 分支时触发
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: FreeBSD VM Build
    steps:
      - uses: actions/checkout@v4

      - name: Setup FreeBSD VM
        uses: vmactions/freebsd-vm@v1
        with:
          release: "14.1"
          usesh: true
          run: |
            pkg install -y node pnpm git

            pnpm install --frozen-lockfile --prod
            pnpm build

            tar -czf directus-freebsd.tar.gz \
              node_modules \
              dist \
              package.json \
              pnpm-lock.yaml

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: directus-freebsd
          path: directus-freebsd.tar.gz
